### PR TITLE
made code more pythonic, add config class

### PR DESCRIPTION
**Pull request by dschwartz783**
### Description
Made code more pythonic, adhering to python's rules of etiquette, and added a ConfigDataProvider class.

### Reason to modify
Code needed a lot of cleanup, and more object-orientedness

### Tests and reviews
Code works.

### CODE REVIEW

**Comment by mhsjlw** [comment]
If you're going to change `camelCase` to `lower_case` please be consistent and use it throughout the code.

**Comment by dschwartz783** [comment]
Just a heads-up. All the code style I made are either highly recommended my Python Enhancement Proposals, or conversion from foreign-language syntax.

**Comment by dschwartz783** [comment]
I can't do anything with the one that must implement methods from PyRakLib. The camelCase style is foreign to python, which prefers lowercase. I can go through it to make things consistent if you want...

**Comment by mhsjlw** [comment]
If it's worth the trouble please rename every function *inside* spiffy to make everything consistent. Don't worry about RakLib for now.

**Comment by mhsjlw** [comment]
Why did you close this pull request? You can just make more commits inside the PR?!

**Comment by dschwartz783** [comment]
Sorry, I'm too grumpy about something else unrelated to code. I shouldn't have changed it all to lowercase XD

**Comment by mhsjlw** [comment]
It's no big deal. At some point we'll write a proper style guide or use https://github.com/google/yapf

**Pull request closed without merging**
